app:
  title: "Payment Processing System"
  description: "Enterprise Payment Processing System API"

data:
  file_path: "payment_information.csv"

server:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 4
  origins:
    - "*"
mongodb:
  uri: "mongodb+srv://rashmi:rashmi@payment-system.9hrxs.mongodb.net/?retryWrites=true&w=majority&appName=payment-system"
  database: "payment_system"
  max_pool_size: 100
  min_pool_size: 10
  timeout_ms: 5000
  collections:
    payments: "payments"
    upload_evidence: "upload_evidence"

logging:
  version: 1
  formatters:
    standard:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: INFO
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: standard
      filename: "app/logs/app.log"
      maxBytes: 10485760 # 10MB
      backupCount: 5
      level: INFO
  root:
    level: INFO
    handlers: [console, file]
